#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "utilities"

KITTY_DIR = File.join(ENV.fetch('XDG_CONFIG_HOME'), 'kitty').freeze

KITTY_COLORS_PATH = File.join(KITTY_DIR, 'colors.conf').freeze

DIFF_COLORS_PATH = File.join(KITTY_DIR, 'diff_colors.conf').freeze

PALETTE = build_palette

kitty_colors = {
  foreground: PALETTE.fetch(:white),
  background: PALETTE.fetch(:black),

  selection_foreground: PALETTE.fetch(:white),
  selection_background: PALETTE.fetch(:dark_gray),

  color0: PALETTE.fetch(:black),
  color8: PALETTE.fetch(:bright_black),

  color1: PALETTE.fetch(:red),
  color9: PALETTE.fetch(:red),

  color2: PALETTE.fetch(:green),
  color10: PALETTE.fetch(:green),

  color3: PALETTE.fetch(:yellow),
  color11: PALETTE.fetch(:yellow),

  color4: PALETTE.fetch(:blue),
  color12: PALETTE.fetch(:blue),

  color5: PALETTE.fetch(:magenta),
  color13: PALETTE.fetch(:magenta),

  color6: PALETTE.fetch(:cyan),
  color14: PALETTE.fetch(:cyan),

  color7: PALETTE.fetch(:white),
  color15: PALETTE.fetch(:bright_white),

  active_tab_foreground: PALETTE.fetch(:magenta),
  active_tab_background: PALETTE.fetch(:darkest_gray),
  inactive_tab_foreground: PALETTE.fetch(:white),
  inactive_tab_background: PALETTE.fetch(:darkest_gray),

  cursor: PALETTE.fetch(:bright_white),
  cursor_text_color: PALETTE.fetch(:black),

  url_color: PALETTE.fetch(:cyan),

  active_border_color: PALETTE.fetch(:green),
  inactive_border_color: PALETTE.fetch(:bright_black),
  bell_border_color: PALETTE.fetch(:red),

  transparent_background_colors: PALETTE
    .values_at(:darkest_gray, :dark_gray, :bright_white, :yellow)
    .join(" "),
}

kitty_diff_colors = {
  foreground: PALETTE.fetch(:white),
  background: PALETTE.fetch(:black),

  title_fg: PALETTE.fetch(:light_gray),
  title_bg: PALETTE.fetch(:darkest_gray),

  margin_fg: PALETTE.fetch(:light_gray),
  margin_bg: PALETTE.fetch(:dark_gray),

  removed_bg: with_alpha(0.1, PALETTE.fetch(:red), PALETTE[:black]),
  highlight_removed_bg: with_alpha(0.2, PALETTE.fetch(:red), PALETTE[:black]),
  removed_margin_bg: with_alpha(0.1, PALETTE.fetch(:red), PALETTE[:darkest_gray]),

  added_bg: with_alpha(0.1, PALETTE.fetch(:green), PALETTE[:black]),
  highlight_added_bg: with_alpha(0.2, PALETTE.fetch(:green), PALETTE[:black]),
  added_margin_bg: with_alpha(0.1, PALETTE.fetch(:green), PALETTE[:darkest_gray]),

  filler_bg: PALETTE.fetch(:darkest_gray),

  hunk_margin_bg: with_alpha(0.2, PALETTE.fetch(:blue), PALETTE[:black]),
  hunk_bg: with_alpha(0.2, PALETTE.fetch(:blue), PALETTE[:darkest_gray]),

  search_fg: PALETTE.fetch(:white),
  search_bg: PALETTE.fetch(:dark_gray),

  select_fg: PALETTE.fetch(:white),
  select_bg: PALETTE.fetch(:dark_gray),
}

File.open(KITTY_COLORS_PATH, 'w') do |f|
  f.puts '# Autogenerated by a tinted-theming hook in'
  f.puts "# #{__FILE__}"
  kitty_colors.each { |kv| f.puts kv.join(' ') }
end

File.open(DIFF_COLORS_PATH, 'w') do |f|
  f.puts '# Autogenerated by a tinted-theming hook in'
  f.puts "# #{__FILE__}"
  kitty_diff_colors.each { |kv| f.puts kv.join(' ') }
end

# `kitty @ --to unix:/tmp/mykitty set-colors --all --configured "#{KITTY_COLORS_PATH}"`
`kitty @ --to unix:/tmp/mykitty load-config`
