#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

UBERSICHT_COLORS_PATH = File.join(
  ENV.fetch("XDG_CONFIG_HOME"),
  "ubersicht",
  "colors.json",
)

def hex_rgb(color, rgb)
  ENV.fetch("TINTY_SCHEME_PALETTE_BASE#{color}_HEX_#{rgb}")
end

# @param color [String] A two-digit string identifying a BASEXX color
# @return [String] Hex string of a color
def get_color(color)
  hex = ["R", "G", "B"].map { |rgb| hex_rgb(color, rgb) }.join
  "##{hex}"
end

File.open(UBERSICHT_COLORS_PATH, 'w') do |f|
  f.puts({
    metadata: {
      created_by: {
        name: __FILE__,
        description: "Autogenerated by a tinted-theming hook",
      },
    },
    Black: get_color("00"),
    BrightBlack: get_color("03"),
    White: get_color("05"),
    BrightWhite: get_color("07"),
    Red: get_color("08"),
    Orange: get_color("09"),
    Yellow: get_color("0A"),
    Green: get_color("0B"),
    Cyan: get_color("0C"),
    Blue: get_color("0D"),
    Magenta: get_color("0E"),
    Brown: get_color("0F"),
  }.to_json)
end
