#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require_relative "utilities"

PALETTE = build_palette

UBERSICHT_COLORS_PATH = File.join(
  ENV.fetch("XDG_CONFIG_HOME"),
  "ubersicht",
  "colors.json",
)

File.open(UBERSICHT_COLORS_PATH, 'w') do |f|
  f.puts({
    metadata: {
      created_by: {
        name: __FILE__,
        description: "Autogenerated by a tinted-theming hook",
      },
    },
    Black: PALETTE.fetch(:black),
    BrightBlack: PALETTE.fetch(:bright_black),
    White: PALETTE.fetch(:white),
    BrightWhite: PALETTE.fetch(:bright_white),
    Red: PALETTE.fetch(:red),
    Orange: PALETTE.fetch(:orange),
    Yellow: PALETTE.fetch(:yellow),
    Green: PALETTE.fetch(:green),
    Cyan: PALETTE.fetch(:cyan),
    Blue: PALETTE.fetch(:blue),
    Magenta: PALETTE.fetch(:magenta),
    Brown: PALETTE.fetch(:brown),
  }.to_json)
end
