#!/usr/bin/env bash

DATE=$(date "+%a %b %d")
TIME=$(date "+%H:%M:%S")

PIANOBAR_ON=$([[ $(pgrep pianobar) ]] && printf 'true' || printf 'false')
SONG=$(cat ~/.config/pianobar/out | grep ' by ' | grep ' on ' | tail -n 1 | sed -e 's/^.*|> //')
SONG=${SONG//'"'/'\"'}

PLUGGED=$([[ $(pmset -g ps | head -1) =~ 'AC' ]] && printf 'true' || printf 'false')
BATTERY=$(pmset -g batt | egrep '(\d+)\%' -o)

BLUETOOTH_POWER=$([[ $(blueutil --power) = 1 ]] && printf 'true' || printf 'false')
BLUETOOTH_CONNECTED=$([[ $(blueutil --paired | grep ', connected') ]] && printf 'true' || printf 'false')

SPACES=$(yabai -m query --spaces 2>/dev/null || printf '[]')

CPUS=$(sysctl -n hw.ncpu)
PERCENT_CPU=$(ps -A -o %cpu | awk '{s+=$1} END {print s}')
LOADAVG=$(sysctl -n vm.loadavg | awk '{print $2}')

# Update the bar colors based on the current base16 theme
COLORS=$(cat ~/.base16_theme |
  grep -e '"../../..".* - ' |
  sed -e 's/.*\(".*"\).* - \(.*\)/"\2":\1/' \
  -e 's/:"/:"#/' \
  -e 's/[\/ ]//g' |
  tr '\n' ',')
COLORS=${COLORS%,} # Remove last comma

cat <<-EOF
{
    "dateTime": {
      "date": "$DATE",
      "time": "$TIME"
    },
    "pianobar": {
      "on": $PIANOBAR_ON,
      "song": "$SONG"
    },
    "power": {
      "plugged": $PLUGGED,
      "battery": "$BATTERY"
    },
    "bluetooth": {
      "on": $BLUETOOTH_POWER,
      "connected": $BLUETOOTH_CONNECTED
    },
    "spaces": $SPACES,
    "cpus": $CPUS,
    "percentCpu": $PERCENT_CPU,
    "loadavg": "$LOADAVG",
    "colors": {$COLORS}
}
EOF
