#!/usr/bin/env bash

if [[ $(arch) = 'i386' ]]; then
  HOMEBREW_PREFIX="/usr/local"
else
  HOMEBREW_PREFIX="/opt/homebrew"
fi

PATH="$PATH:$HOMEBREW_PREFIX/bin" # So yabai will be in our path

DATE=$(date "+%a %b %d")
TIME=$(date "+%H:%M")

PIANOBAR_ON=$([[ $(pgrep pianobar) ]] && printf 'true' || printf 'false')
SONG=$(cat ~/.config/pianobar/out | grep ' by ' | grep ' on ' | tail -n 1 | sed -e 's/^.*|> //')
SONG=${SONG//'"'/'\"'}

PLUGGED=$([[ $(pmset -g ps | head -1) =~ 'AC' ]] && printf 'true' || printf 'false')
BATTERY=$(pmset -g batt | egrep '(\d+)\%' -o)

SPACES=$(yabai -m query --spaces 2>/dev/null || printf '[]')
WINDOWS=$(yabai -m query --windows 2>/dev/null || printf '[]')
DISPLAYS=$(yabai -m query --displays 2>/dev/null || printf '[]')

CPUS=$(sysctl -n hw.ncpu)
PERCENT_CPU=$(ps -A -o %cpu | awk '{s+=$1} END {print s}')
LOADAVG=$(sysctl -n vm.loadavg | awk '{print $2}')

AUDIO_OUT=$(SwitchAudioSource -c -t output -f json)
AUDIO_IN=$(SwitchAudioSource -c -t input -f json)

# Update the bar colors based on the current theme
COLORS=$(cat ~/.config/ubersicht/colors.json)

cat <<-EOF
{
    "dateTime": {
      "date": "$DATE",
      "time": "$TIME"
    },
    "pianobar": {
      "on": $PIANOBAR_ON,
      "song": "$SONG"
    },
    "power": {
      "plugged": $PLUGGED,
      "battery": "$BATTERY"
    },
    "spaces": $SPACES,
    "windows": $WINDOWS,
    "displays": $DISPLAYS,
    "cpus": $CPUS,
    "percentCpu": $PERCENT_CPU,
    "loadavg": "$LOADAVG",
    "audio": {
      "out": $AUDIO_OUT,
      "in": $AUDIO_IN
    },
    "colors": $COLORS
}
EOF
