[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.profile ] && source ~/.profile

# Use zplug to manage zsh plugins: https://github.com/zplug/zplug
export ZPLUG_HOME=/usr/local/opt/zplug
[ -f $ZPLUG_HOME/init.zsh ] && source $ZPLUG_HOME/init.zsh

# Base16 Shell
export BASE16_SHELL="$ZPLUG_HOME/repos/chriskempson/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"
export BASE16_SHELL_HOOKS="$XDG_CONFIG_HOME/base16-shell-hooks"

# Edit this file more easily
alias ez="$EDITOR ~/.zshrc; source ~/.zshrc; echo \".zshrc edited and sourced\""

# Common emacs bindings for vi mode
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^P' up-line-or-history
bindkey '^N' down-line-or-history
bindkey '^[^M' self-insert-unmeta # Insert newline w/out running command

# Enable autocompletion
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -Uz compinit
compinit

# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

# Report command running time if it is more than 5 seconds
REPORTTIME=5
# Keep a lot of history
HISTFILE=~/.zhistory
HISTSIZE=5000
SAVEHIST=5000
# Add commands to history as they are entered, don't wait for shell to exit
setopt SHARE_HISTORY
# Also remember command start time and duration
setopt EXTENDED_HISTORY
# Do not keep duplicate commands in history
setopt HIST_IGNORE_ALL_DUPS
# Do not remember commands that start with a whitespace
setopt HIST_IGNORE_SPACE
# Enable autocompletion
zstyle ':completion:*' completer _complete _correct _approximate
zstyle ':completion:*' menu select
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

source $XDG_CONFIG_HOME/purepower

# zsh plugins
zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme
zplug "lukechilds/zsh-nvm"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug load
# There's a kitty-themes repo that stores a bunch of themes in kitty .conf
# format. I'd like to transition to using that, but Base16 integrates nicely
# into (n)vim. See: https://github.com/dexpota/kitty-themes
# Also, this is *after* `zplug load` because it's not really a zsh plugin...
zplug "chriskempson/base16-shell"
