# Use the rubocop defaults as much as possible and support multiple versions of
# ruby/rubocop by keeping this file mostly empty.
#
# For rubocop's defaults, see:
# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/MethodParameterName:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/AsciiComments:
  Enabled: false
