# Use the rubocop defaults as much as possible and support multiple versions of
# ruby/rubocop by keeping this file mostly empty.
#
# For rubocop's defaults, see:
# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

AllCops:
  NewCops: enable

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: true
  Max: 100

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/MethodParameterName:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/AsciiComments:
  Enabled: false

Lint/SafeNavigationChain:
  AllowedMethods:
    - present?
    - blank?
    - presence
    - try
    - try!
    - in?
    - to_maybe

Naming/AccessorMethodName:
  Enabled: false
