#!/usr/bin/env bash

tmpfile='/tmp/sleepwatcher.bluetooth.info'

[[ -f "$tmpfile" ]] && rm "$tmpfile"

if [[ "$(blueutil --power)" = 1 ]]; then
  blueutil --paired |
    grep ', connected' |
    sed -e 's/,.*//g' -e 's/address: //g' > "$tmpfile"

  blueutil --power 0
fi

pgrep pianobar > /dev/null && pkill pianobar
