#!/usr/bin/env bash

tmpfile='/tmp/sleepwatcher.bluetooth.info'

if [[ -f "$tmpfile" ]]; then
  blueutil -p 1
  # sleep to give bluetooth time to turn on before connecting
  sleep 1
  for id in $(cat "$tmpfile"); do
    blueutil --connect "$id"
  done
fi

rm "$tmpfile"
